# Generated by Django 3.0.7 on 2020-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200707_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order_id',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='order_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='Порядок в меню'),
        ),
    ]
