# Generated by Django 3.0.7 on 2020-07-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200707_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='subtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='Подзаголовок статьи'),
        ),
    ]
