# Generated by Django 3.0.7 on 2020-07-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_articles_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drink',
            field=models.BooleanField(default=False, verbose_name='Напиток'),
        ),
    ]
